#!/bin/bash 
# Dependencies: tesseract-ocr imagemagick scrot xsel
SCR_IMG=`mktemp`
trap "rm $SCR_IMG*" EXIT
scrot -s $SCR_IMG.png -q 100    
mogrify -modulate 100,0 -resize 400% $SCR_IMG.png 
tesseract -l 'eng' $SCR_IMG.png $SCR_IMG &> /dev/null
cat $SCR_IMG.txt | xsel -bi
cat $SCR_IMG.txt
exit
